'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const {spawn}=require('node:child_process');
const {tokensFromReply,AccountStore,planAllowed}=require('../src/auth/accounts');const {withFileLock}=require('../src/auth/lock');const {BridgeError,delay}=require('../src/util');const {createAccounts,seed,mockResponse}=require('./helpers.cjs');const C=require('../src/constants');
test('token response uses granted scopes, not requested scopes',()=>{const t=tokensFromReply({access_token:'a',token_type:'Bearer',expires_in:3600,id_token:'id',scope:'openid email'});assert.equal(planAllowed(t),false);assert.deepEqual(t.scopes,['openid','email']);});
test('refresh preserves scope only when server omits scope, and keeps session identity',()=>{const prior={scopes:C.SCOPES,sessionId:'same',idToken:'old'};const t=tokensFromReply({access_token:'new',refresh_token:'new-r',token_type:'Bearer',expires_in:3600},prior);assert.equal(t.sessionId,'same');assert.equal(t.idToken,'old');assert.deepEqual(t.scopes,C.SCOPES);assert.equal(planAllowed(t),true);});
test('missing token expiration and wrong token type fail closed',()=>{assert.throws(()=>tokensFromReply({access_token:'a',token_type:'Bearer'}),{code:'bad_token_response'});assert.throws(()=>tokensFromReply({access_token:'a',token_type:'MAC',expires_in:3600}),{code:'bad_token_response'});});
test('host identity persists across store reconstruction',async t=>{const a=await createAccounts(t,async()=>{throw 0;});const b=new AccountStore(a.secrets,a.dir);assert.equal(await b.init(),a.store.hostId);assert.match(b.hostId,/^urn:uuid:/);});
test('15 concurrent accesses rotate refresh token only once',async t=>{let calls=0;const{accounts,store}=await createAccounts(t,async(url,opts)=>{calls++;assert.equal(url,C.TOKEN_URL);const form=new URLSearchParams(opts.body);assert.equal(form.get('client_id'),'oaiapp_account-a');assert.equal(form.has('scope'),false);await delay(10);return mockResponse(200,{access_token:'new',refresh_token:'rotated',token_type:'Bearer',expires_in:3600});});await seed(store,{expiresAt:Date.now()-1});const results=await Promise.all(Array.from({length:15},()=>accounts.access()));assert.equal(calls,1);assert.ok(results.every(x=>x.accessToken==='new'));const p=(await store.read()).profiles[0];assert.equal(p.tokens.refreshToken,'rotated');});
test('multi-process lock serializes independent Node processes',async t=>{const{dir}=await createAccounts(t,async()=>{throw 0;});const counter=path.join(dir,'counter.json');await fs.writeFile(counter,'0');const lockModule=require.resolve('../src/auth/lock');const js=`const {withFileLock}=require(${JSON.stringify(lockModule)});const fs=require('node:fs/promises');(async()=>{for(let i=0;i<4;i++)await withFileLock(${JSON.stringify(path.join(dir,'cross-process.lock'))},async()=>{const n=Number(await fs.readFile(${JSON.stringify(counter)},'utf8'));await new Promise(r=>setTimeout(r,4));await fs.writeFile(${JSON.stringify(counter)},String(n+1));});})().catch(e=>{console.error(e);process.exitCode=1;});`;
  await Promise.all(Array.from({length:5},()=>new Promise((resolve,reject)=>{const c=spawn(process.execPath,['-e',js],{stdio:['ignore','ignore','pipe']});let err='';c.stderr.on('data',b=>err+=b);c.on('error',reject);c.on('exit',code=>code===0?resolve():reject(new Error(err)));})));assert.equal(Number(await fs.readFile(counter,'utf8')),20);
});
test('temporary refresh failure preserves credentials and registration',async t=>{const{accounts,store}=await createAccounts(t,async()=>mockResponse(503,{detail:'temporary'}));await seed(store,{expiresAt:Date.now()-1});await assert.rejects(accounts.access(),{status:503});const p=(await store.read()).profiles[0];assert.equal(p.state,'signedIn');assert.equal(p.tokens.refreshToken,'old-refresh');});
for(const code of ['invalid_grant','refresh_token_reused','refresh_token_expired'])test(`terminal ${code} clears unusable tokens but keeps issued client`,async t=>{const{accounts,store}=await createAccounts(t,async()=>mockResponse(400,{error:code}));await seed(store,{expiresAt:Date.now()-1});await assert.rejects(accounts.access(),{code});const p=(await store.read()).profiles[0];assert.equal(p.tokens,null);assert.equal(p.clientId,'oaiapp_account-a');assert.equal(p.state,'signedOut');});
test('early refresh hint defers renewal while old token is still valid',async t=>{let calls=0;const{accounts,store}=await createAccounts(t,async()=>{calls++;throw 0;});await seed(store,{expiresAt:Date.now()+30000});const db=await store.read();db.profiles[0].tokens.earliestRefreshAt=Date.now()+20000;await store.save(db);assert.equal((await accounts.access()).accessToken,'old-access');assert.equal(calls,0);});
test('missing direct permission never reaches inference/auth transport',async t=>{let calls=0;const{accounts,store}=await createAccounts(t,async()=>{calls++;throw 0;});await seed(store,{scopes:['openid']});await assert.rejects(accounts.access(),{code:'plan_permission_missing'});assert.equal(calls,0);});
test('sign-out sends refresh-token revocation and retains mapping and host',async t=>{let sent;const{accounts,store}=await createAccounts(t,async(url,options)=>{sent={url,form:new URLSearchParams(options.body)};return mockResponse(200,'');});await seed(store);const host=store.hostId;assert.equal((await accounts.signOut()).revoked,true);assert.equal(sent.form.get('token'),'old-refresh');assert.equal(sent.form.get('token_type_hint'),'refresh_token');assert.equal(sent.form.get('client_id'),'oaiapp_account-a');const p=(await store.read()).profiles[0];assert.equal(p.tokens,null);assert.equal(p.clientId,'oaiapp_account-a');assert.equal(store.hostId,host);});
test('unconfirmed revocation clears local tokens and reports uncertainty',async t=>{const{accounts,store}=await createAccounts(t,async()=>{throw new BridgeError('network',{code:'network_error'});});await seed(store);assert.equal((await accounts.signOut()).revoked,false);assert.equal((await store.read()).profiles[0].tokens,null);});
test('active account switch invalidates prior response lease',async t=>{const{accounts,store}=await createAccounts(t,async()=>{throw 0;});await seed(store);const old=await accounts.access();await seed(store,{id:'account-b',sessionId:'session-b'});await assert.rejects(accounts.assertLease(old),{code:'account_changed'});});
test('secret storage is the only location containing tokens',async t=>{const{store,dir,secrets}=await createAccounts(t,async()=>{throw 0;});await seed(store);const files=await fs.readdir(dir);for(const f of files){const st=await fs.stat(path.join(dir,f));if(st.isFile())assert.ok(!(await fs.readFile(path.join(dir,f),'utf8')).includes('old-access'));}assert.ok((await secrets.get(C.SECRET_KEY)).includes('old-access'));});
test('same-process live lock is never stolen at timeout',async t=>{const{dir}=await createAccounts(t,async()=>{throw 0;});const lock=path.join(dir,'busy.lock');await fs.mkdir(lock);await fs.writeFile(path.join(lock,'owner.json'),JSON.stringify({pid:process.pid,nonce:'owner'}));await assert.rejects(withFileLock(lock,async()=>{throw new Error('stolen');},undefined,60),{code:'credential_lock_timeout'});assert.equal(JSON.parse(await fs.readFile(path.join(lock,'owner.json'),'utf8')).nonce,'owner');});
test('missing host identity with existing registrations fails closed instead of changing host binding',async t=>{const {store,dir}=await createAccounts(t,async()=>{throw new Error('not called');});await seed(store);await fs.rm(path.join(dir,'host.json'));await assert.rejects(store.init(),{code:'host_state_error'});});
test('full Accounts sign-in stores a verified registration and reuses it without bootstrap on return',async t=>{
  const C=require('../src/constants');let authUrl,exchanges=0;
  const oidc={validate:async(_token,e)=>{assert.equal(e.nonce,authUrl.searchParams.get('nonce'));assert.equal(e.clientId,'oaiapp_new_registration');return{sub:'verified-user',email:'local@example.invalid'};}};
  const {accounts,store}=await createAccounts(t,async(url,options)=>{assert.equal(url,C.TOKEN_URL);assert.equal(new URLSearchParams(options.body).get('client_id'),'oaiapp_new_registration');exchanges++;return mockResponse(200,{access_token:'new-access',refresh_token:'new-refresh',id_token:'mock-id-token',token_type:'Bearer',expires_in:3600,scope:C.SCOPES.join(' ')});},oidc);
  accounts.openBrowser=async url=>{authUrl=new URL(url);await fetch(authUrl.searchParams.get('redirect_uri')+'?state='+authUrl.searchParams.get('state')+'&code=issued-code&client_id=oaiapp_new_registration');return true;};
  const first=await accounts.signIn();assert.equal(first.planEnabled,true);const db=await store.read();assert.equal(db.profiles.length,1);assert.equal(db.pending.length,0);assert.equal(db.profiles[0].subject,'verified-user');assert.equal(db.profiles[0].tokens.refreshToken,'new-refresh');
  await accounts.signIn(first.id,true);assert.equal(authUrl.searchParams.get('client_id'),'oaiapp_new_registration');assert.equal(authUrl.searchParams.has('agent_name_hint'),false);assert.equal(authUrl.searchParams.get('prompt'),'consent');assert.equal((await store.read()).profiles.length,1);assert.equal(exchanges,2);
});
test('identity-only sign-in remains stored but cannot spend plan usage',async t=>{
  const {accounts,store}=await createAccounts(t,async()=>mockResponse(200,{access_token:'identity-access',id_token:'identity-token',token_type:'Bearer',expires_in:3600,scope:'openid profile email'}),{validate:async()=>({sub:'identity'})});
  accounts.openBrowser=async url=>{const u=new URL(url);await fetch(u.searchParams.get('redirect_uri')+'?state='+u.searchParams.get('state')+'&code=c&client_id=oaiapp_identity');return true;};
  assert.equal((await accounts.signIn()).planEnabled,false);assert.equal((await store.read()).profiles[0].state,'signedIn');await assert.rejects(accounts.access(),{code:'plan_permission_missing'});
});
test('failed token exchange retains issued registration as incomplete and never enables inference',async t=>{
  const {accounts,store}=await createAccounts(t,async()=>mockResponse(503,{detail:'temporary'}));accounts.openBrowser=async url=>{const u=new URL(url);await fetch(u.searchParams.get('redirect_uri')+'?state='+u.searchParams.get('state')+'&code=c&client_id=oaiapp_pending');return true;};
  await assert.rejects(accounts.signIn(),{status:503});const db=await store.read();assert.equal(db.profiles.length,0);assert.equal(db.pending[0].clientId,'oaiapp_pending');assert.equal(db.active,null);
});
test('same verified email may have distinct client registrations without replacing credentials',async t=>{
  let count=0;const {accounts,store}=await createAccounts(t,async()=>mockResponse(200,{access_token:'a'+count,refresh_token:'r'+count,id_token:'id',token_type:'Bearer',expires_in:3600,scope:C.SCOPES.join(' ')}),{validate:async()=>({sub:'same-subject',email:'same@example.invalid'})});
  accounts.openBrowser=async url=>{count++;const u=new URL(url);await fetch(u.searchParams.get('redirect_uri')+'?state='+u.searchParams.get('state')+'&code=c&client_id=oaiapp_distinct_'+count);return true;};
  const a=await accounts.signIn(),b=await accounts.signIn();assert.notEqual(a.id,b.id);const db=await store.read();assert.equal(db.profiles.length,2);assert.notEqual(db.profiles[0].label,db.profiles[1].label);assert.notEqual(db.profiles[0].tokens.accessToken,db.profiles[1].tokens.accessToken);await accounts.select(a.id);assert.equal((await accounts.active()).id,a.id);
});
