'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {Readable}=require('node:stream');
const {wireName,buildTools,parseCall}=require('../src/protocol/tools');
const {ResponseReplayCache,convertMessages,estimateTokens}=require('../src/protocol/history');
const {parseSSE,consumeResponse}=require('../src/protocol/sse');
const {remoteError}=require('../src/util');
const {normalizeCatalog,modelInfo}=require('../src/openai/models');
const {sse,done,call,tools}=require('./helpers.cjs');
function history(name='read_file',input={path:'a.txt'}){return[{role:1,content:[{value:'Read it'}]},{role:2,content:[{value:'Reading.'},{callId:'call_1',name,input}]},{role:1,content:[{callId:'call_1',content:[{value:'file contents'}]},{value:'Continue'}]}];}
async function consume(events,options={}){let text='';const response=sse(events,options);const result=await consumeResponse(response,{onText:x=>{text+=x;},remoteError});return{...result,text};}
test('functions are grouped into a namespace; optional properties remain optional',()=>{const built=buildTools(tools);assert.equal(built.tools[0].type,'namespace');assert.equal(built.tools[0].name,'vscode');assert.equal(built.tools[0].tools[0].strict,false);assert.equal(built.tools[0].tools[0].parameters,tools[0].inputSchema);assert.equal(built.mapping.get('read_file'),'read_file');});
test('nonconforming tool names have deterministic reversible mapping and <=64 wire characters',()=>{const name='mcp.azure@tool/'+ 'a'.repeat(120);const built=buildTools([{name}]);const wire=[...built.mapping.keys()][0];assert.match(wire,/^[A-Za-z0-9_-]{1,64}$/);assert.equal(wire,wireName(name));assert.notEqual(wire,wireName(name+'b'));assert.deepEqual(parseCall(call('call_1',wire),built.mapping),{callId:'call_1',name,input:{path:'a.txt'}});});
test('duplicate/colliding supplied tools are rejected',()=>{assert.throws(()=>buildTools([...tools,...tools]),{code:'invalid_tool'});const n='mcp.tools/read';assert.throws(()=>buildTools([{name:n},{name:wireName(n)}]),{code:'invalid_tool'});});
for(const [name,item,code] of [
 ['unknown name',call('c','not_allowed'),'unadvertised_tool'],['unknown namespace',{...call(),namespace:'remote'},'unadvertised_tool'],['invalid JSON',call('c','read_file','{'),'invalid_tool_arguments'],['array args',call('c','read_file','[]'),'invalid_tool_arguments'],['null args',call('c','read_file','null'),'invalid_tool_arguments'],['missing ID',{...call(),call_id:''},'invalid_tool_call']
])test(`tool-call validation rejects ${name}`,()=>assert.throws(()=>parseCall(item,buildTools(tools).mapping),{code}));
test('full tool history preserves interleaved text, calls, results and following input',()=>{const converted=convertMessages(history());assert.equal(converted.length,5);assert.equal(converted[0].content[0].text,'Read it');assert.equal(converted[1].role,'assistant');assert.equal(converted[2].namespace,'vscode');assert.equal(converted[3].type,'function_call_output');assert.equal(converted[3].output,'file contents');assert.equal(converted[4].content[0].text,'Continue');});
test('native System=3 input is encoded as developer with its instructions preserved',()=>{const out=convertMessages([{role:3,content:[{value:'instructions'}]},{role:1,content:[{value:'hi'}]}]);assert.deepEqual(out,[{role:'developer',content:[{type:'input_text',text:'instructions'}]},{role:'user',content:[{type:'input_text',text:'hi'}]}]);});
test('assistant text without replay state uses the supported string history form',()=>{
  const out=convertMessages([{role:1,content:[{value:'Question'}]},{role:2,content:[{value:'First '},{value:'answer'}]},{role:1,content:[{value:'Continue'}]}],{cache:new ResponseReplayCache(),scope:'changed-model'});
  assert.deepEqual(out[1],{role:'assistant',content:'First answer'});
  assert.deepEqual(out[0].content,[{type:'input_text',text:'Question'}]);
  assert.deepEqual(out[2].content,[{type:'input_text',text:'Continue'}]);
});
for(const [name,messages] of [
 ['orphan result',[{role:1,content:[{callId:'orphan',content:[{value:'x'}]}]}]],
 ['missing result',history().slice(0,2)],
 ['duplicate result',[...history(),history()[2]]],
 ['duplicate call',[...history().slice(0,2),history()[1],history()[2]]]
])test(`broken tool history rejects ${name}`,()=>assert.throws(()=>convertMessages(messages),{code:'invalid_tool_history'}));
test('unknown message parts are rejected rather than silently discarded',()=>assert.throws(()=>convertMessages([{role:1,content:[{unknown:'data'}]}]),{code:'unsupported_input'}));
test('image input is inline and capability gated; arbitrary file uploads are rejected',()=>{const message=[{role:1,content:[{data:Buffer.from([0,1,2]),mimeType:'image/png'}]}];assert.throws(()=>convertMessages(message),{code:'unsupported_image'});assert.equal(convertMessages(message,{imageAllowed:true})[0].content[0].image_url,'data:image/png;base64,AAEC');assert.throws(()=>convertMessages([{role:1,content:[{data:Buffer.from('pdf'),mimeType:'application/pdf'}]}]),{code:'unsupported_input'});});
test('text and JSON binary parts are lossless UTF8',()=>{const converted=convertMessages([{role:1,content:[{mimeType:'text/plain',data:Buffer.from('中文🙂')},{mimeType:'application/json',data:Buffer.from('{"x":1}')}]}]);assert.equal(converted[0].content[0].text,'中文🙂');assert.equal(converted[0].content[1].text,'{"x":1}');});
test('image tool results use a content array instead of destroying data',()=>{const h=history();h[2].content[0].content.push({data:Buffer.from([1,2]),mimeType:'image/png'});assert.equal(convertMessages(h,{imageAllowed:true})[3].output[1].type,'input_image');});
test('complete tool response is replayed only for matching account/model/history',()=>{const cache=new ResponseReplayCache();const reasoning={type:'reasoning',id:'rs1',encrypted_content:'opaque-test-ciphertext',summary:[]};const message={type:'message',id:'m1',role:'assistant',phase:'commentary',content:[{type:'output_text',text:'Reading.'}]};const output=[reasoning,message,call()];cache.remember('scope',history().slice(0,1),output,buildTools(tools).mapping);const out=convertMessages(history(),{cache,scope:'scope'});assert.deepEqual(out.slice(1,4),output);assert.equal(convertMessages(history(),{cache,scope:'another-account'}).some(i=>i.type==='reasoning'),false);assert.equal(convertMessages(history('read_file',{path:'changed'}),{cache,scope:'scope'}).some(i=>i.type==='reasoning'),false);});
test('parallel calls sharing reasoning replay the complete response once',()=>{const cache=new ResponseReplayCache();const r={type:'reasoning',id:'rs1',encrypted_content:'cipher',summary:[]};const message={type:'message',role:'assistant',phase:'commentary',content:[{type:'output_text',text:'Reading.'}]};cache.remember('scope',history().slice(0,1),[r,message,call(),call('call_2')],buildTools(tools).mapping);const h=history();h[1].content.push({callId:'call_2',name:'read_file',input:{path:'a.txt'}});h[2].content.push({callId:'call_2',content:[{value:'second'}]});assert.equal(convertMessages(h,{cache,scope:'scope'}).filter(i=>i.type==='reasoning').length,1);});
test('response replay cache is bounded and explicitly clearable',()=>{const cache=new ResponseReplayCache(1024);cache.remember('scope',history().slice(0,1),[{type:'reasoning',id:'r',encrypted_content:'x'.repeat(5000)},call()],buildTools(tools).mapping);assert.equal(cache.entries.size,0);const bigger=new ResponseReplayCache();bigger.remember('scope',history().slice(0,1),[call()],buildTools(tools).mapping);assert.ok(bigger.bytes>0);bigger.clear();assert.equal(bigger.bytes,0);assert.equal(bigger.entries.size,0);});
test('text token counting follows UTF8 byte length divided by four',()=>{assert.equal(estimateTokens('中文🙂'),3);assert.equal(estimateTokens('x'.repeat(40960)),10240);assert.ok(estimateTokens(history()[1])>10);});
test('model catalog is account-specific, visibility-filtered, de-duplicated and ordered',()=>{const models=normalizeCatalog({models:[{slug:'hidden',visibility:'hide'},{slug:'first',display_name:'First',visibility:'list',context_window:200000,max_output_tokens:30000,input_modalities:['image'],supported_reasoning_levels:[{effort:'high'}]},{slug:'second',visibility:'list'},{slug:'first',visibility:'list'}]});assert.deepEqual(models.map(m=>m.id),['first','second']);assert.equal(models[0].maxInputTokens,170000);assert.equal(models[0].limitsEstimated,false);assert.equal(models[0].capabilities.imageInput,true);assert.deepEqual(models[0].efforts,['high']);assert.equal(models[1].limitsEstimated,true);assert.equal(modelInfo(models[0]).efforts,undefined);});
test('API-key catalog shape is not silently accepted for SIWC',()=>assert.throws(()=>normalizeCatalog({data:[{id:'model'}]}),{code:'invalid_model_catalog'}));
test('no visible models produces an explicit error',()=>assert.throws(()=>normalizeCatalog({models:[]}),{code:'no_visible_models'}));
test('SSE handles 1-byte UTF8 chunks and does not duplicate final item text',async()=>{const message={type:'message',id:'m',content:[{type:'output_text',text:'中文🙂'}]};const r=await consume([{type:'response.output_text.delta',item_id:'m',content_index:0,delta:'中'},{type:'response.output_text.delta',item_id:'m',content_index:0,delta:'文🙂'},{type:'response.output_item.done',output_index:0,item:message},done([message])],{chunkSize:1});assert.equal(r.text,'中文🙂');});
test('SSE parser accepts comments, multiline data, CR and LF',async()=>{const input=Buffer.from(': keepalive\r\nevent: event-name\r\ndata: {"a":\r\ndata: 1}\r\n\r\ndata: second\r\r');const events=[];for await(const e of parseSSE(Readable.from([...input].map(b=>Buffer.from([b])))))events.push(e);assert.deepEqual(events,[{event:'event-name',data:'{"a":\n1}'},{event:'',data:'second'}]);});
test('SSE text is recovered from completed output if no deltas arrived',async()=>{const r=await consume([done([{type:'message',id:'m',content:[{type:'output_text',text:'Only final'}]}])]);assert.equal(r.text,'Only final');});
test('SSE incomplete frames and DONE markers are not completion',async()=>{await assert.rejects(consume(['data: [DONE]\n\n']),{code:'stream_interrupted'});await assert.rejects(consume(['data: {"type":"response.completed"}']),{code:'stream_interrupted'});});
test('completed output, not function arguments event metadata, supplies tool identity',async()=>{const r=await consume([{type:'response.function_call_arguments.done',item_id:'fc_call_1',arguments:'{"path":"a.txt"}'},{type:'response.output_item.done',output_index:0,item:call()},done([call()])]);assert.equal(r.output[0].name,'read_file');});
for(const [name,events,code] of [
 ['failure after output',[{type:'response.output_text.delta',item_id:'m',delta:'partial'}, {type:'response.failed',response:{error:{code:'subscription_sharing_usage_limit_exceeded'}}}],'subscription_sharing_usage_limit_exceeded'],
 ['top-level error',[{type:'error',code:'subscription_sharing_usage_limit_exceeded'}],'subscription_sharing_usage_limit_exceeded'],
 ['incomplete',[{type:'response.incomplete'}],'response_incomplete'],
 ['invalid JSON',['data: {bad}\n\n'],'invalid_stream'],
 ['hosted execution',[done([{type:'computer_call',id:'x'}])],'unsupported_output']
])test(`SSE rejects ${name}`,async()=>assert.rejects(consume(events),{code}));
test('SSE enforces a per-frame byte bound',async()=>{await assert.rejects(async()=>{for await(const _ of parseSSE(Readable.from(['data: '+ 'x'.repeat(100)+'\n\n']),undefined,32)){void _;}},{code:'stream_too_large'});});
