'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {EventEmitter}=require('node:events');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const Module=require('node:module');
const {Provider}=require('../src/vscode/provider');const {OpenAIClient}=require('../src/openai/client');const {BridgeError}=require('../src/util');const C=require('../src/constants');
const {model,messages,tools,lease,sse,done,call,fakeVscode,token,MemorySecrets}=require('./helpers.cjs');
function setup(t,client){const fake=fakeVscode(),accounts=new EventEmitter();let active={id:lease.accountId,sessionId:lease.sessionId,state:'signedIn',planEnabled:true};accounts.active=async()=>active;accounts.access=async()=>{if(!active)throw new BridgeError('Sign in required.',{code:'sign_in_required'});return lease;};accounts.assertLease=async l=>{if(!active||l.accountId!==active.id||l.sessionId!==active.sessionId)throw new BridgeError('Account changed.',{code:'account_changed'});};const logs=[];const provider=new Provider(fake.vscode,accounts,client||{models:async()=>[model]},async()=>{},e=>logs.push(e));t.after(()=>provider.dispose());return{...fake,provider,accounts,logs,setActive:v=>{active=v;accounts.emit('change');}};}
test('unsigned silent model discovery neither starts login nor touches network',async t=>{let n=0;const s=setup(t,{models:async()=>{n++;return[model];}});s.setActive(null);assert.deepEqual(await s.provider.provideLanguageModelChatInformation({silent:true},token()),[]);assert.equal(n,0);});
test('model information uses stable fields and caches discovery',async t=>{let n=0;const s=setup(t,{models:async()=>{n++;return[model];}});await s.provider.accountChanged();const a=await s.provider.provideLanguageModelChatInformation({silent:true},token());await s.provider.provideLanguageModelChatInformation({silent:true},token());assert.equal(n,1);assert.equal(a[0].id,model.id);assert.equal(a[0].efforts,undefined);s.provider.refresh();await s.provider.provideLanguageModelChatInformation({silent:true},token());assert.equal(n,2);});
test('native provider streams TextPart and emits ToolCallPart only after completed response',async t=>{const client=new OpenAIClient(async()=>sse([{type:'response.output_text.delta',item_id:'m',delta:'Read it'},{type:'response.output_item.done',output_index:0,item:call()},done([call()])]));client.models=async()=>[model];const s=setup(t,client);const progress=[];await s.provider.provideLanguageModelChatResponse(model,messages,{tools,toolMode:1},{report:p=>progress.push(p)},token());assert.equal(progress[0] instanceof s.vscode.LanguageModelTextPart,true);assert.equal(progress[1] instanceof s.vscode.LanguageModelToolCallPart,true);assert.equal(progress[1].name,'read_file');assert.equal(progress.length,2);assert.equal(s.vscode.lm.invokeTool,undefined);});
test('completed response with a later invalid tool never leaks the earlier valid tool to the host',async t=>{const client=new OpenAIClient(async()=>sse([done([call(),call('c2','unknown_tool')])]));client.models=async()=>[model];const s=setup(t,client),progress=[];await assert.rejects(s.provider.provideLanguageModelChatResponse(model,messages,{tools},{report:p=>progress.push(p)},token()),{code:'unadvertised_tool'});assert.equal(progress.length,0);});
test('mid-stream failure after text and staged tool does not emit ToolCallPart',async t=>{const client=new OpenAIClient(async()=>sse([{type:'response.output_text.delta',item_id:'m',delta:'partial'},{type:'response.output_item.done',output_index:0,item:call()},{type:'response.failed',response:{error:{code:'subscription_sharing_usage_limit_exceeded'}}}]));client.models=async()=>[model];const s=setup(t,client),progress=[];await assert.rejects(s.provider.provideLanguageModelChatResponse(model,messages,{tools},{report:p=>progress.push(p)},token()),{code:'subscription_sharing_usage_limit_exceeded'});assert.equal(progress.length,1);assert.equal(progress[0] instanceof s.vscode.LanguageModelTextPart,true);});
test('caller cancellation stops inference and withholds tool execution',async t=>{let entered;const started=new Promise(r=>{entered=r;});const client={models:async()=>[model],infer:async(_l,_m,_h,_o,{signal})=>{entered();await new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true}));}};const s=setup(t,client),ct=token(),parts=[];const pending=s.provider.provideLanguageModelChatResponse(model,messages,{tools},{report:p=>parts.push(p)},ct);await started;ct.cancel();await assert.rejects(pending,{name:'Canceled'});assert.equal(parts.length,0);assert.equal(s.provider.controllers.size,0);});
test('switching account during a request cancels the request and clears ephemeral reasoning',async t=>{let entered;const started=new Promise(r=>{entered=r;});const client={models:async()=>[model],infer:async(_l,_m,_h,_o,{signal})=>{entered();await new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true}));}};const s=setup(t,client);const pending=s.provider.provideLanguageModelChatResponse(model,messages,{}, {report(){}},token());await started;s.setActive({id:'another',sessionId:'new',state:'signedIn',planEnabled:true});await assert.rejects(pending,{name:'Canceled'});assert.equal(s.provider.cache.entries.size,0);});
test('untrusted workspace is denied before inference',async t=>{let called=false;const s=setup(t,{infer:async()=>{called=true;}});s.vscode.workspace.isTrusted=false;await assert.rejects(s.provider.provideLanguageModelChatResponse(model,messages,{}, {report(){}},token()),{code:'workspace_untrusted'});assert.equal(called,false);});
test('model disappearing from catalog is not silently replaced',async t=>{const s=setup(t,{models:async()=>[model]});await assert.rejects(s.provider.provideLanguageModelChatResponse({...model,id:'missing'},messages,{}, {report(){}},token()),{code:'model_unavailable'});});
test('token-count cancellation is propagated to the host',async t=>{const s=setup(t),ct=token();ct.cancel();await assert.rejects(s.provider.provideTokenCount(model,'input',ct),{name:'Canceled'});});
test('complete two-turn agent protocol keeps tool execution in the caller and replays reasoning',async t=>{let requestNumber=0;const client=new OpenAIClient(async(_url,options)=>{const body=JSON.parse(options.body);if(++requestNumber===1)return sse([done([{type:'reasoning',id:'rs',encrypted_content:'encrypted-test-content',summary:[]},call()])]);assert.equal(body.input.some(i=>i.type==='reasoning'&&i.encrypted_content==='encrypted-test-content'),true);assert.equal(body.input.some(i=>i.type==='function_call_output'&&i.call_id==='call_1'&&i.output==='host-provided result'),true);return sse([done([{type:'message',id:'m2',content:[{type:'output_text',text:'Finished using the result.'}]}])]);});client.models=async()=>[model];const s=setup(t,client),first=[];await s.provider.provideLanguageModelChatResponse(model,messages,{tools},{report:p=>first.push(p)},token());assert.equal(first[0].name,'read_file');const history=[...messages,{role:2,content:first},{role:1,content:[{callId:first[0].callId,content:[{value:'host-provided result'}]}]}];let text='';await s.provider.provideLanguageModelChatResponse(model,history,{tools},{report:p=>{text+=p.value||'';}},token());assert.equal(text,'Finished using the result.');assert.equal(requestNumber,2);});
test('actual extension entry point activates against a VS Code API mock and registers every manifest command',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'bridge-activation-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const fake=fakeVscode(),original=Module._load;const file=require.resolve('../src/extension');delete require.cache[file];let extension;try{Module._load=function(id,parent,isMain){return id==='vscode'?fake.vscode:original.call(this,id,parent,isMain);};extension=require(file);}finally{Module._load=original;}
const context={subscriptions:[],secrets:new MemorySecrets(),globalStorageUri:{fsPath:dir}};t.after(()=>{for(const d of [...context.subscriptions].reverse())d.dispose();delete require.cache[file];});assert.equal((await extension.activate(context)).version,C.VERSION);const manifest=require('../package.json');for(const command of manifest.contributes.commands)assert.equal(fake.commands.has(command.command),true,command.command);assert.equal(fake.registrations.some(r=>r.kind==='lm'&&r.id===C.VENDOR),true);assert.equal(fake.registrations.some(r=>r.kind==='auth'&&r.id===C.AUTH_PROVIDER),true);const lm=fake.registrations.find(r=>r.kind==='lm').provider;assert.deepEqual(await lm.provideLanguageModelChatInformation({silent:true},token()),[]);await fake.commands.get('chatgptDirect.diagnostics')();assert.equal(fake.notifications.some(s=>s.includes('accessToken')),false);
});
